First draft where all the tracking logic is implemented
viam-modules/re-id-object-tracking pull request #1
Opened 2024-08-28 18:03 UTC by Rob1in

Things still in progress and follow-up PRs:

- Please ignore all the build stuffs (`requirements.txt` and `build.sh`) because it still has to be figured out. I can add executables if needed. 
- README.md
- Add more models, but the packaging in a "one-file PyInstaller" is there
- Testing
- Some TODOs are written

2024-08-28 18:14 UTC, Rob1in commented on src/config/config.py
This is an attempt to improve readability and maintainability of config attributes. It goes together with the attribute.py file that enables standardized validation depending on the types of the attribute.

2024-08-28 18:15 UTC, Rob1in commented on src/re_id_tracker.py
> +            return [Classification(class_name="new_object_detected", confidence=1)]
It's a TODO to decide what should be the confidence. I think it should be something like the inverse of the distance more than the confidence of the detector.

2024-08-28 18:16 UTC, Rob1in commented on src/tracker/detector.py
> +MODEL_NAME_TO_MODEL_RELATIVE_PATH = {
There is a TODO to add more models from mediapipe

2024-08-28 18:17 UTC, Rob1in commented on src/tracker/encoder.py
> +
same here, I will add the other model from `torchreid`

2024-08-28 18:18 UTC, Rob1in commented on src/tracker/tracker.py
> +            confidence=1,
same than above for the `confidence`

2024-08-29 15:30 UTC, Rob1in commented on src/tracker/tracker.py
> +                # TODO: figure out this 30
This is basically a normalization. The embeddings outputted by the encoder are not normalized, so I found this value empirically (see the Alex/Robin experimentations). I plan to test it out better once the tracker is running in a "top-view" camera

2024-09-04 17:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/viamrobotics/re-id-object-tracking?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/viamrobotics/re-id-object-tracking?pullRequest=1) before we can accept your contribution.<br/><hr/>**Robin In** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/viamrobotics/re-id-object-tracking?pullRequest=1) it.</sub>

2024-09-05 13:45 UTC, Rob1in commented
Follow-up PR: 

- adding other detectors
- adding other encoders
- introduce the notion of persistance of an entity so we have more control over notifications
- filter int the cost matrix all columns (=detections) and rows (tracks) that are above `min_confidence_threshold`
- fix "normalization" parameters for encoder ( int the `src.Tracker.Encoder.compute_distance()`)

2024-09-06 15:20 UTC, bhaney requested changes
Looking good, the meat of this looks nice, it's just small things, and some notes for a later versions

2024-09-06 15:20 UTC, bhaney commented on src/tracker/tracker.py
> +    def update(self, img, visualize: bool = False):
Very cool function! I could tell this probably took a long time to get right

2024-09-11 14:13 UTC, Rob1in commented on src/re_id_tracker.py
> +        camera_name = config.attributes.fields["camera_name"].string_value
done

2024-09-11 14:38 UTC, Rob1in commented
We have a `TracksManager` which is in charge of the serialization of `Tracks` and the sync of the database on disk and some of the trackers objects (bbox, embedding).
The database contains 2 tables.

1. `tracks` :  [`id`, `bbox`, `embedding`]
2. `category_count` :  [`category`, `count`] to store the `integer` part of the string unique id of a track. (person_**N**_date_time)


As of today, the sync logic is like this:

-  The only moment where tracks on disk are loaded to the tracker is at the beginning. I think it should stay like that to avoid conflicts. 
- Once, the background loop is started, the tracks are serialized and written on disk. The frequency of the `save to disk` operation is  controlled by the new attribute `save_period`. 


Follow up:
- Maybe adding a column time of update in `tracks` table which seems to be a good practice for debugging
- Database of map person_name -> track-id
- debug and logging configuration
- Figuring out parameters for confidence threshold for each models
- Code cleaning and standardization
- README

2024-09-12 20:15 UTC, bhaney requested changes
cool - just one request to remove the assert statement and replace it with an if statement and exception

2024-09-12 20:15 UTC, bhaney commented on src/tracker/tracks_manager.py
> +        assert len(serialized_track) == 3
rather than an assert statement, create an if statement, and throw an exception with an error

2024-09-12 20:15 UTC, bhaney commented on src/tracker/tracks_manager.py
Eventually, a future TODO will be an option to prune old tracks. I think right now it's OK and there won't be a risk of filling up the space/memory.

2024-09-12 20:15 UTC, bhaney commented on src/tracker/tracks_manager.py
> +            id CHAR PRIMARY KEY,
Nice, I also agree that using the original person_timestamp string is a good key to use across tables

2024-09-18 16:46 UTC, merged