Add torchvision build
viam-modules/re-id-object-tracking pull request #19
Opened 2024-12-19 21:58 UTC by Rob1in

2025-01-06 19:04 UTC, nicksanford commented
you have merge conflicts

2025-01-06 19:04 UTC, nicksanford commented on Makefile
> +#TODO: ADD PHONY install-cudnn
can we do this?

2025-01-06 19:33 UTC, nicksanford commented
on my orin this fails with this error:
```
viam@nicks-orin-nano-1:~/re-id-object-tracking$ make pyinstaller
Installing cudnn 9
bin/first_run.sh
Installing the required libraries for the 're-id-object-tracking' module...
Checking if libcudnn.so.9 is installed...
libcudnn.so.9 is already installed.
No installation needed.
All required libraries for the 're-id-object-tracking' module have been installed successfully.
Making /home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
wget  -P /home/viam/re-id-object-tracking/build https://developer.download.nvidia.com/compute/redist/jp/v61/pytorch/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
--2025-01-06 14:30:47--  https://developer.download.nvidia.com/compute/redist/jp/v61/pytorch/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 184.28.190.51, 184.28.190.48
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|184.28.190.51|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 806950107 (770M) [text/plain]
Saving to: ‘/home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl’

torch-2.5.0a0+872d972e41.nv24.08.17622132-cp3 100%[==============================================================================================>] 769.57M  41.5MB/s    in 22s

2025-01-06 14:31:09 (34.6 MB/s) - ‘/home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl’ saved [806950107/806950107]

Installing dependencies for TorchVision
/home/viam/re-id-object-tracking/build/.venv/bin/python -m pip install --upgrade pip
Requirement already satisfied: pip in ./build/.venv/lib/python3.10/site-packages (22.0.2)
Collecting pip
  Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 20.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-24.3.1
/home/viam/re-id-object-tracking/build/.venv/bin/python -m pip install wheel
Collecting wheel
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
Installing collected packages: wheel
Successfully installed wheel-0.45.1
/home/viam/re-id-object-tracking/build/.venv/bin/python -m pip install 'numpy<2' /home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
Processing ./build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
Collecting numpy<2
  Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (62 kB)
Collecting filelock (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
  Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions>=4.8.0 (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting networkx (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
  Downloading jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Collecting sympy==1.13.1 (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch==2.5.0a0+872d972e41.nv24.08.17622132)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.5.0a0+872d972e41.nv24.08.17622132)
  Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (4.0 kB)
Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 77.1 MB/s eta 0:00:00
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 71.7 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
Downloading jinja2-3.1.5-py3-none-any.whl (134 kB)
Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 43.0 MB/s eta 0:00:00
Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (21 kB)
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 19.0 MB/s eta 0:00:00
Installing collected packages: mpmath, typing-extensions, sympy, numpy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch
Successfully installed MarkupSafe-3.0.2 filelock-3.16.1 fsspec-2024.12.0 jinja2-3.1.5 mpmath-1.3.0 networkx-3.4.2 numpy-1.26.4 sympy-1.13.1 torch-2.5.0a0+872d972e41.nv24.8 typing-extensions-4.12.2
Cloning Torchvision
git clone --branch v0.20.0 --recursive --depth=1 https://github.com/pytorch/vision  /home/viam/re-id-object-tracking/build/torchvision
Cloning into '/home/viam/re-id-object-tracking/build/torchvision'...
remote: Enumerating objects: 928, done.
remote: Counting objects: 100% (928/928), done.
remote: Compressing objects: 100% (762/762), done.
remote: Total 928 (delta 207), reused 467 (delta 140), pack-reused 0 (from 0)
Receiving objects: 100% (928/928), 12.70 MiB | 29.03 MiB/s, done.
Resolving deltas: 100% (207/207), done.
Note: switching to 'afc54f754c734d903a06194e416495e20d920ff6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Building torchvision wheel
cd /home/viam/re-id-object-tracking/build/torchvision && /home/viam/re-id-object-tracking/build/.venv/bin/python setup.py --verbose bdist_wheel --dist-dir ../
/home/viam/re-id-object-tracking/build/torchvision/setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.command.clean
Traceback (most recent call last):
  File "/home/viam/re-id-object-tracking/build/torchvision/setup.py", line 11, in <module>
    import torch
  File "/home/viam/re-id-object-tracking/build/.venv/lib/python3.10/site-packages/torch/__init__.py", line 361, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcusparseLt.so.0: cannot open shared object file: No such file or directory
make: *** [Makefile:48: /home/viam/re-id-object-tracking/build/torchvision-0.20.0a0+afc54f7-cp310-cp310-linux_aarch64.whl] Error 1

```

2025-01-06 19:33 UTC, nicksanford requested changes

2025-01-06 19:33 UTC, nicksanford commented on README.md
> +## PyInstaller Build Process
can we please have 2 targets:
1. make
2. make clean
 

1 should build the project
2 should clean the project

2025-01-06 19:33 UTC, nicksanford commented on Makefile
> +install-cudnn:
this should detect if `first_run.sh` has already succeeded and if so, not run

2025-01-06 19:33 UTC, nicksanford commented on README.md
> +make clean-pyinstaller
this target doesn't exist

2025-02-03 19:54 UTC, Rob1in commented on requirements.txt
> -torch==2.0
done! Since the torch, torchvision and onnx were built from local wheels, I just changed the explicit path to relative from what `pip freeze` gave me

2025-02-03 19:59 UTC, Rob1in commented
> on my orin this fails with this error:
> 
> ```
> viam@nicks-orin-nano-1:~/re-id-object-tracking$ make pyinstaller
> Installing cudnn 9
> bin/first_run.sh
> Installing the required libraries for the 're-id-object-tracking' module...
> Checking if libcudnn.so.9 is installed...
> libcudnn.so.9 is already installed.
> No installation needed.
> All required libraries for the 're-id-object-tracking' module have been installed successfully.
> Making /home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
> wget  -P /home/viam/re-id-object-tracking/build https://developer.download.nvidia.com/compute/redist/jp/v61/pytorch/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
> --2025-01-06 14:30:47--  https://developer.download.nvidia.com/compute/redist/jp/v61/pytorch/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
> Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 184.28.190.51, 184.28.190.48
> Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|184.28.190.51|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 806950107 (770M) [text/plain]
> Saving to: ‘/home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl’
> 
> torch-2.5.0a0+872d972e41.nv24.08.17622132-cp3 100%[==============================================================================================>] 769.57M  41.5MB/s    in 22s
> 
> 2025-01-06 14:31:09 (34.6 MB/s) - ‘/home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl’ saved [806950107/806950107]
> 
> Installing dependencies for TorchVision
> /home/viam/re-id-object-tracking/build/.venv/bin/python -m pip install --upgrade pip
> Requirement already satisfied: pip in ./build/.venv/lib/python3.10/site-packages (22.0.2)
> Collecting pip
>   Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 20.9 MB/s eta 0:00:00
> Installing collected packages: pip
>   Attempting uninstall: pip
>     Found existing installation: pip 22.0.2
>     Uninstalling pip-22.0.2:
>       Successfully uninstalled pip-22.0.2
> Successfully installed pip-24.3.1
> /home/viam/re-id-object-tracking/build/.venv/bin/python -m pip install wheel
> Collecting wheel
>   Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
> Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
> Installing collected packages: wheel
> Successfully installed wheel-0.45.1
> /home/viam/re-id-object-tracking/build/.venv/bin/python -m pip install 'numpy<2' /home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
> Processing ./build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
> Collecting numpy<2
>   Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (62 kB)
> Collecting filelock (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
>   Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
> Collecting typing-extensions>=4.8.0 (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
>   Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
> Collecting networkx (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
>   Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
> Collecting jinja2 (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
>   Downloading jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
> Collecting fsspec (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
>   Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
> Collecting sympy==1.13.1 (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
>   Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
> Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch==2.5.0a0+872d972e41.nv24.08.17622132)
>   Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
> Collecting MarkupSafe>=2.0 (from jinja2->torch==2.5.0a0+872d972e41.nv24.08.17622132)
>   Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (4.0 kB)
> Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.2 MB)
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 77.1 MB/s eta 0:00:00
> Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 71.7 MB/s eta 0:00:00
> Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
> Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
> Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
> Downloading jinja2-3.1.5-py3-none-any.whl (134 kB)
> Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 43.0 MB/s eta 0:00:00
> Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (21 kB)
> Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 19.0 MB/s eta 0:00:00
> Installing collected packages: mpmath, typing-extensions, sympy, numpy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch
> Successfully installed MarkupSafe-3.0.2 filelock-3.16.1 fsspec-2024.12.0 jinja2-3.1.5 mpmath-1.3.0 networkx-3.4.2 numpy-1.26.4 sympy-1.13.1 torch-2.5.0a0+872d972e41.nv24.8 typing-extensions-4.12.2
> Cloning Torchvision
> git clone --branch v0.20.0 --recursive --depth=1 https://github.com/pytorch/vision  /home/viam/re-id-object-tracking/build/torchvision
> Cloning into '/home/viam/re-id-object-tracking/build/torchvision'...
> remote: Enumerating objects: 928, done.
> remote: Counting objects: 100% (928/928), done.
> remote: Compressing objects: 100% (762/762), done.
> remote: Total 928 (delta 207), reused 467 (delta 140), pack-reused 0 (from 0)
> Receiving objects: 100% (928/928), 12.70 MiB | 29.03 MiB/s, done.
> Resolving deltas: 100% (207/207), done.
> Note: switching to 'afc54f754c734d903a06194e416495e20d920ff6'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> Building torchvision wheel
> cd /home/viam/re-id-object-tracking/build/torchvision && /home/viam/re-id-object-tracking/build/.venv/bin/python setup.py --verbose bdist_wheel --dist-dir ../
> /home/viam/re-id-object-tracking/build/torchvision/setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
>   import distutils.command.clean
> Traceback (most recent call last):
>   File "/home/viam/re-id-object-tracking/build/torchvision/setup.py", line 11, in <module>
>     import torch
>   File "/home/viam/re-id-object-tracking/build/.venv/lib/python3.10/site-packages/torch/__init__.py", line 361, in <module>
>     from torch._C import *  # noqa: F403
> ImportError: libcusparseLt.so.0: cannot open shared object file: No such file or directory
> make: *** [Makefile:48: /home/viam/re-id-object-tracking/build/torchvision-0.20.0a0+afc54f7-cp310-cp310-linux_aarch64.whl] Error 1
> ```

Added a script in [this commit](https://github.com/viam-modules/re-id-object-tracking/pull/19/commits/e37331fee7c5b36ff9fd74bc7cd249d133f3279f). Figuring out now if it should also be part of a first_run.sh script, feels like it, but never failed because of cuSPARSELt when deployed on fresh orins. I guess it depends on how it's flashed..?

2025-02-04 19:05 UTC, Rob1in commented
> > on my orin this fails with this error:
> > ```
> > viam@nicks-orin-nano-1:~/re-id-object-tracking$ make pyinstaller
> > Installing cudnn 9
> > bin/first_run.sh
> > Installing the required libraries for the 're-id-object-tracking' module...
> > Checking if libcudnn.so.9 is installed...
> > libcudnn.so.9 is already installed.
> > No installation needed.
> > All required libraries for the 're-id-object-tracking' module have been installed successfully.
> > Making /home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
> > wget  -P /home/viam/re-id-object-tracking/build https://developer.download.nvidia.com/compute/redist/jp/v61/pytorch/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
> > --2025-01-06 14:30:47--  https://developer.download.nvidia.com/compute/redist/jp/v61/pytorch/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
> > Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 184.28.190.51, 184.28.190.48
> > Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|184.28.190.51|:443... connected.
> > HTTP request sent, awaiting response... 200 OK
> > Length: 806950107 (770M) [text/plain]
> > Saving to: ‘/home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl’
> > 
> > torch-2.5.0a0+872d972e41.nv24.08.17622132-cp3 100%[==============================================================================================>] 769.57M  41.5MB/s    in 22s
> > 
> > 2025-01-06 14:31:09 (34.6 MB/s) - ‘/home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl’ saved [806950107/806950107]
> > 
> > Installing dependencies for TorchVision
> > /home/viam/re-id-object-tracking/build/.venv/bin/python -m pip install --upgrade pip
> > Requirement already satisfied: pip in ./build/.venv/lib/python3.10/site-packages (22.0.2)
> > Collecting pip
> >   Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
> >      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 20.9 MB/s eta 0:00:00
> > Installing collected packages: pip
> >   Attempting uninstall: pip
> >     Found existing installation: pip 22.0.2
> >     Uninstalling pip-22.0.2:
> >       Successfully uninstalled pip-22.0.2
> > Successfully installed pip-24.3.1
> > /home/viam/re-id-object-tracking/build/.venv/bin/python -m pip install wheel
> > Collecting wheel
> >   Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
> > Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
> > Installing collected packages: wheel
> > Successfully installed wheel-0.45.1
> > /home/viam/re-id-object-tracking/build/.venv/bin/python -m pip install 'numpy<2' /home/viam/re-id-object-tracking/build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
> > Processing ./build/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl
> > Collecting numpy<2
> >   Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (62 kB)
> > Collecting filelock (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
> >   Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
> > Collecting typing-extensions>=4.8.0 (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
> >   Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
> > Collecting networkx (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
> >   Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
> > Collecting jinja2 (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
> >   Downloading jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
> > Collecting fsspec (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
> >   Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
> > Collecting sympy==1.13.1 (from torch==2.5.0a0+872d972e41.nv24.08.17622132)
> >   Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
> > Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch==2.5.0a0+872d972e41.nv24.08.17622132)
> >   Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
> > Collecting MarkupSafe>=2.0 (from jinja2->torch==2.5.0a0+872d972e41.nv24.08.17622132)
> >   Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (4.0 kB)
> > Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.2 MB)
> >    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 77.1 MB/s eta 0:00:00
> > Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
> >    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 71.7 MB/s eta 0:00:00
> > Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
> > Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
> > Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
> > Downloading jinja2-3.1.5-py3-none-any.whl (134 kB)
> > Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
> >    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 43.0 MB/s eta 0:00:00
> > Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (21 kB)
> > Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
> >    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 19.0 MB/s eta 0:00:00
> > Installing collected packages: mpmath, typing-extensions, sympy, numpy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch
> > Successfully installed MarkupSafe-3.0.2 filelock-3.16.1 fsspec-2024.12.0 jinja2-3.1.5 mpmath-1.3.0 networkx-3.4.2 numpy-1.26.4 sympy-1.13.1 torch-2.5.0a0+872d972e41.nv24.8 typing-extensions-4.12.2
> > Cloning Torchvision
> > git clone --branch v0.20.0 --recursive --depth=1 https://github.com/pytorch/vision  /home/viam/re-id-object-tracking/build/torchvision
> > Cloning into '/home/viam/re-id-object-tracking/build/torchvision'...
> > remote: Enumerating objects: 928, done.
> > remote: Counting objects: 100% (928/928), done.
> > remote: Compressing objects: 100% (762/762), done.
> > remote: Total 928 (delta 207), reused 467 (delta 140), pack-reused 0 (from 0)
> > Receiving objects: 100% (928/928), 12.70 MiB | 29.03 MiB/s, done.
> > Resolving deltas: 100% (207/207), done.
> > Note: switching to 'afc54f754c734d903a06194e416495e20d920ff6'.
> > 
> > You are in 'detached HEAD' state. You can look around, make experimental
> > changes and commit them, and you can discard any commits you make in this
> > state without impacting any branches by switching back to a branch.
> > 
> > If you want to create a new branch to retain commits you create, you may
> > do so (now or later) by using -c with the switch command. Example:
> > 
> >   git switch -c <new-branch-name>
> > 
> > Or undo this operation with:
> > 
> >   git switch -
> > 
> > Turn off this advice by setting config variable advice.detachedHead to false
> > 
> > Building torchvision wheel
> > cd /home/viam/re-id-object-tracking/build/torchvision && /home/viam/re-id-object-tracking/build/.venv/bin/python setup.py --verbose bdist_wheel --dist-dir ../
> > /home/viam/re-id-object-tracking/build/torchvision/setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
> >   import distutils.command.clean
> > Traceback (most recent call last):
> >   File "/home/viam/re-id-object-tracking/build/torchvision/setup.py", line 11, in <module>
> >     import torch
> >   File "/home/viam/re-id-object-tracking/build/.venv/lib/python3.10/site-packages/torch/__init__.py", line 361, in <module>
> >     from torch._C import *  # noqa: F403
> > ImportError: libcusparseLt.so.0: cannot open shared object file: No such file or directory
> > make: *** [Makefile:48: /home/viam/re-id-object-tracking/build/torchvision-0.20.0a0+afc54f7-cp310-cp310-linux_aarch64.whl] Error 1
> > ```
> 
> Added a script in [this commit](https://github.com/viam-modules/re-id-object-tracking/pull/19/commits/e37331fee7c5b36ff9fd74bc7cd249 [...]

2025-02-04 19:17 UTC, Rob1in commented on README.md
> +make clean-pyinstaller
fixed and added 2 clean targets (`clean-setup` and `clean-pyinstaller`)

2025-02-04 20:07 UTC, Rob1in commented on Makefile
> +#TODO: ADD PHONY install-cudnn
I have removed the target that I originally made to install system dependencies ( including `install-cudnn`).

I install the system dependencies in the instructions for building the targets that needs them and I made sure that the the scripts for installing check if it already ran (or to be precise, if the libraries are already there). 

The PHONY targets are now `setup clean pyinstaller clean-pyinstaller`  + _fictional_ targets (= aliases that makes the makefile easier to test)

2025-02-20 19:05 UTC, bhaney approved these changes
Went through the Makefile commands with Alan to build the module. There will be some extra things to do, but for now we will merge this into main

2025-02-26 18:40 UTC, merged